export const ON_ERROR = 'ON_ERROR';
export const ON_PRODUCTS = 'ON_PRODUCTS';
export const ON_SUCCESS_GET_PRODUCTS = 'ON_SUCCESS_GET_PRODUCTS';
export const ON_SUCCESS_GET_PRODUCT = 'ON_SUCCESS_GET_PRODUCT';
export const ON_SUCCESS_DELETE_PRODUCT = 'ON_SUCCESS_DELETE_PRODUCT';
export const ON_SUCCESS_UPDATE_PRODUCT = 'ON_SUCCESS_UPDATE_PRODUCT'